name: ai_movie_suggestion
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  http: ^1.4.0
  rxdart: ^0.28.0
  logarte: ^0.3.1
  lottie: ^3.2.0
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  analyzer: ^6.7.0

  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^19.3.1
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  retrofit_generator:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon" # Or true to use default filename
  ios: true
  image_path: "assets/AppIcons/icon.png"
flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/Logo.png
    - assets/images/success.png
    - assets/images/Mail.png
    - assets/images/me.jpg
    - assets/images/icons/splashLogo.png
    - assets/images/onboarding/onBoarding1.png
    - assets/images/onboarding/onBoarding2.png
    - assets/images/onboarding/onBoarding3.png
    - assets/json/loading.json
    - assets/json/loading2.json
    - assets/json/loadingDots.json
    - assets/json/success.json
    - assets/json/error.json

    
    - assets/images/icons/Home.png
    - assets/images/icons/Sparkles.png
    - assets/images/icons/Compass.png
    - assets/images/icons/User.png
    - assets/images/icons/Home_active.png
    - assets/images/icons/Sparkles_active.png
    - assets/images/icons/Compass_active.png
    - assets/images/icons/User_active.png
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
